//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComparableGenerator {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnalyzerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalyzerResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComparableGenerator.AnalyzerResources", typeof(AnalyzerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Type that declares CompareByAttribute should declare ComparableAttribute. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DescriptionWhereComparableIsNotDefined {
            get {
                return ResourceManager.GetString("DescriptionWhereComparableIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type that declares ComparableAttribute should declare CompareByAttribute for any members. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DescriptionWhereCompareByIsNotDefined {
            get {
                return ResourceManager.GetString("DescriptionWhereCompareByIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type that declares ComparableAttribute should declare CompareByAttribute for any members. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DescriptionWhereMemberWithSamePriority {
            get {
                return ResourceManager.GetString("DescriptionWhereMemberWithSamePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Members that declare CompareByAttribute must implement IComparable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DescriptionWhereNotImplementedIComparable {
            get {
                return ResourceManager.GetString("DescriptionWhereNotImplementedIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type &quot;{0}.{1}&quot; does not declare ComparableAttribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFormatWhereComparableIsNotDefined {
            get {
                return ResourceManager.GetString("MessageFormatWhereComparableIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type &quot;{0}.{1}&quot; does not have any member with CompareByAttribute declared に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFormatWhereCompareByIsNotDefined {
            get {
                return ResourceManager.GetString("MessageFormatWhereCompareByIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type &quot;{0}.{1}&quot; does not declare ComparableAttribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFormatWhereMemberWithSamePriority {
            get {
                return ResourceManager.GetString("MessageFormatWhereMemberWithSamePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; does not implemented IComparable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFormatWhereNotImplementedIComparable {
            get {
                return ResourceManager.GetString("MessageFormatWhereNotImplementedIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type does not declare ComparableAttribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleWhereComparableIsNotDefined {
            get {
                return ResourceManager.GetString("TitleWhereComparableIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type does not have any member with CompareByAttribute declared に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleWhereCompareByIsNotDefined {
            get {
                return ResourceManager.GetString("TitleWhereCompareByIsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type does not declare ComparableAttribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleWhereMemberWithSamePriority {
            get {
                return ResourceManager.GetString("TitleWhereMemberWithSamePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Member does not implemented IComparable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleWhereNotImplementedIComparabl {
            get {
                return ResourceManager.GetString("TitleWhereNotImplementedIComparabl", resourceCulture);
            }
        }
    }
}
